- packages/cf-component-copyable-textarea/src/CopyableTextarea.js
Congrats on the OSS release! 🔥 
It would be nice if `CopyableTextArea` let you respond to a successful copy event. This makes that happen.
I tried adding a test, but there aren't any tests for `CopyableTextArea` at all and karma was giving me some trouble, so I'll have to figure that out.
> Add onCopy prop to CopyableTextArea

- packages/cf-builder-pagination/README.md
- packages/cf-builder-pagination/example/basic/component.js
- packages/cf-builder-table/example/basic/component.js
- packages/cf-component-button/example/basic/component.js
- packages/cf-component-card/example/basic/component.js
- packages/cf-component-checkbox/README.md
- packages/cf-component-checkbox/example/basic/component.js
- packages/cf-component-dropdown/README.md
- packages/cf-component-dropdown/example/basic/component.js
- packages/cf-component-form/example/basic/component.js
- packages/cf-component-input/README.md
- packages/cf-component-input/example/basic/component.js
- packages/cf-component-link/example/basic/component.js
- packages/cf-component-modal/README.md
- packages/cf-component-modal/example/basic/component.js
- packages/cf-component-notifications/README.md
- packages/cf-component-notifications/example/basic/component.js
- packages/cf-component-pagination/README.md
- packages/cf-component-pagination/example/basic/component.js
- packages/cf-component-progress/example/basic/component.js
- packages/cf-component-radio/README.md
- packages/cf-component-radio/example/basic/component.js
- packages/cf-component-select/example/basic/component.js
- packages/cf-component-tabs/README.md
- packages/cf-component-tabs/example/basic/component.js
- packages/cf-component-textarea/README.md
- packages/cf-component-textarea/example/basic/component.js
- packages/cf-component-toggle/README.md
- packages/cf-component-toggle/example/basic/component.js
The previous PR removed dependency `babel-preset-cf` and broke the examples, this fixes them.
> Convert class properties to plain ES6 in examples

- lerna.json
- package.json
So `npm run bootstrap` doesn't die anymore
> Upgrade to lerna beta 31

- packages/cf-component-form/src/FormFieldError.js
- packages/cf-component-form/test/FormFieldError.js
We don't need to return <noscript> in react 15 anymore.
> Remove noscript

- packages/cf-component-table/src/Table.js
- packages/cf-component-table/src/TableBody.js
- packages/cf-component-table/src/TableCell.js
- packages/cf-component-table/src/TableFoot.js
- packages/cf-component-table/src/TableHead.js
- packages/cf-component-table/src/TableHeadCell.js
- packages/cf-component-table/src/TableRow.js
- packages/cf-component-table/test/Table.js
- packages/cf-component-table/test/TableBody.js
- packages/cf-component-table/test/TableCell.js
- packages/cf-component-table/test/TableFoot.js
- packages/cf-component-table/test/TableHead.js
- packages/cf-component-table/test/TableHeadCell.js
- packages/cf-component-table/test/TableRow.js
This is a part of #33 
Sometimes, we'll need to have CSS classes that target the rows and columns. Since technically the HTML spec doesn't allow us to wrap elements around `<tr>`,`<th>` and `<td>`, we have to use custom class names to avoid having a mess of CSS selectors all over the place.
This PR fixes this issue.
> Optional custom class names for table components

- packages/cf-component-copyable-textarea/package.json
- packages/cf-component-copyable-textarea/src/CopyableTextarea.js
- packages/cf-component-copyable-textarea/test/CopyableTextarea.js
React 15 upgrade broke CopyableTextarea and I didn't catch this because there were no tests. The ref returned was the Component instead of the wrapped DOM element, which has `focus()` and `select()`.
This rewrote CopyableTextarea to be more straightforward. An `onClick` prop has been added to Textarea as well to enable copying the programmatically selected text from CopyableTextarea.
You can also supply the help text from the props, just like what the README says.
> Fix issue with not being able to focus and select the textarea

- packages/cf-component-select/README.md
- packages/cf-component-select/example/basic/component.js
- packages/cf-component-select/src/Select.js
Our implementation of `cf-component-select` allows us to pass in options with `disabled: true`, but we don't document this anywhere.
> Document 'disabled' option for cf-component-select

- packages/cf-component-textarea/src/Textarea.js
I noticed this when publishing 🙃
> [TextArea] Add `className` to props validation

- packages/cf-component-select/src/Select.js
Cache is now a object in `react-select` as well as being set to a empty object in `react-select` :tophat:
https://github.com/JedWatson/react-select/blob/master/src/Async.js#L5-L45
> Remove `cache` default prop `true`

- packages/cf-component-tabs/src/Tabs.js
- packages/cf-component-tabs/src/TabsPanel.js
- packages/cf-component-tabs/test/Tabs.js
- packages/cf-component-tabs/test/TabsPanel.js
`cf-component-tabs` would render all the tabpanel components when a tab component would get rendered. This has the potential of loading a bunch of data over the network that the user will never see.
By changing it this way we are able to only request the data needed to render the tabs the user actually clicks on
> Don't render tab panels unless they are clicked

- package.json
- packages/cf-component-modal/package.json
- packages/cf-component-modal/test/__snapshots__/ModalTitle.js.snap
Lerna bumped heading's major version (fela version) and now cf-component-modal is failing in www-next because there is no fela yet. So I'm lowering the heading version to pre-fela version.
> Fix heading version in modal

- packages/cf-component-heading/src/Heading.js
- packages/cf-component-heading/src/HeadingCaption.js
- packages/cf-component-heading/test/Heading.js
- packages/cf-component-heading/test/HeadingCaption.js
- packages/cf-component-text/src/Text.js
- packages/cf-component-text/src/TextTheme.js
- packages/cf-component-text/test/Text.js
- packages/cf-component-text/test/__snapshots__/Text.js.snap
according to feedback from @tajo:
* using plain object for applying styles
* exports components as `TextUnstyled`, `HeaderUnstyled` in tests to follow same style
* fix for text titlecase
* fix for text small size
> Refactor cf-component-text, cf-component-header, small bugfixes

- packages/cf-component-modal/package.json
- packages/cf-component-modal/src/ModalTitle.js
- packages/cf-component-modal/test/__snapshots__/ModalTitle.js.snap
There is no reason why old components couldn't consume new Fela components if Fela is supported in www-next now. It's critical to not pin cross dependencies in order to make lerna and our workflow happy.
Heading is bumped to v3 (fela version) in cf-component-modal, so the theme needs to be applied. We still major bump cf-component-modal so it doesn't break anything.
> Unpin cf-component-heading in cf-component-modal

- packages/cf-util-http/src/http.js
- packages/cf-util-http/test/http.js
This should make cf-util-http users happier.
> #129 allow null as the 3rd parameter again

- packages/cf-util-http/src/http.js
- packages/cf-util-http/test/http.js
This is rather urgent as some internal code just assumes the body will be automatically encoded
> Emulate superagent's automatic encoding of JSON body

- packages/cf-util-http/src/http.js
- packages/cf-util-http/test/http.js
This should be the last fix for cf-util-http where people were taking advantage of superagent's ability to filter out null headers and now have the their APIs broken by fetch.
> Emulate superagent's ability to filter out headers with null or undefined values

- README.md
- example/package.json
- example/source.js
- example/yarn.lock
- `cf-style-container v0.2.0` was missing peerDependency `fela`, fixed in `v0.2.1`, the example's yarn.lock needs to be updated
- don't use relative path for `cf-style-provider`, the example should have no dependencies to the rest of cf-ui repo
> Fix example and use absolute path to cf-style-provider

- packages/cf-component-button/README.md
- packages/cf-component-button/example/basic/component.js
- packages/cf-component-button/src/index.js
- packages/cf-component-button/test/Button.js
- packages/cf-component-button/test/ButtonGroup.js
- packages/cf-component-heading/README.md
- packages/cf-component-heading/example/basic/component.js
- packages/cf-component-heading/src/index.js
- packages/cf-component-heading/test/Heading.js
- packages/cf-component-heading/test/HeadingCaption.js
- packages/cf-component-modal/src/ModalTitle.js
- packages/cf-component-text/README.md
- packages/cf-component-text/example/basic/component.js
- packages/cf-component-text/src/index.js
- packages/cf-component-text/test/Text.js
The reasoning is here: https://github.com/cloudflare/cf-ui/issues/136
**TLDR;** Let's make our life easier. No need to ever change APIs because of Fela migration.
Major bumps for: 
- cf-component-button
- cf-component-heading
- cf-component-text
Minor bump for:
- cf-component-modal
> Export styled components by default

- packages/cf-util-http/src/http.js
- packages/cf-util-http/test/http.js
This fixes an issue described in https://github.com/cloudflare/cf-ui/issues/139 where our detection of whether to parse a response `body` as JSON relied on strict string matching, rather than emulating how it's handled in `superagent`.
The practice for bumping the version isn't defined in CONTRIBUTING, so I won't include it here, but 🙏 *please please please please* 🙏 publish as a `PATCH`, as per the [Semver FAQ](http://semver.org/#what-if-i-inadvertently-alter-the-public-api-in-a-way-that-is-not-compliant-with-the-version-number-change-ie-the-code-incorrectly-introduces-a-major-breaking-change-in-a-patch-release).
> Fix JSON content-type detection in 'wrapResponse'

- packages/cf-util-http/src/http.js
- packages/cf-util-http/test/http.js
* #139 Fix JSON content-type detection in 'wrapResponse'
* add test for json content type in the response and add credentials to same origin by default
> Fix JSON content-type detection in 'wrapResponse' (#140)

- packages/cf-component-card/src/CardDrawers.js
- packages/cf-component-card/test/CardDrawers.js
- packages/cf-component-card/test/__snapshots__/CardDrawers.js.snap
Whenever you're using the `CardDrawers` sub-component of `Card` you need
to add some keys to your state and handle all the events yourself. This
is fine if you want to control the flow very tightly but the most common
case is just to switch to the drawers selected.
This patch changes the `CardDrawers` sub-component so it still takes in
the props and those will control the component but falls back to the
local state if the props `active` and `onClick` are not present.
Not sure if there are more tests to be written or if the snapshots are enough.
> card: Keep a local state of drawers if no props

- packages/cf-util-http/src/http.js
avoid use of Headers.entries() and for .. of because of limited support in Edge browser.
more details: https://developer.mozilla.org/en-US/docs/Web/API/Headers\#Browser_compatibility
> Fixes cf-util-http in Edge

- packages/cf-builder-card/README.md
- packages/cf-builder-card/example/basic/component.js
- packages/cf-builder-table/README.md
- packages/cf-builder-table/example/basic/component.js
- packages/cf-component-card/README.md
- packages/cf-component-card/example/basic/component.js
- packages/cf-component-dropdown/README.md
- packages/cf-component-dropdown/example/basic/component.js
- packages/cf-component-modal/README.md
- packages/cf-component-modal/example/basic/component.js
- packages/cf-component-notifications/README.md
- packages/cf-component-notifications/example/basic/component.js
**This doesn't change any component.** `cf-component-button` exports the styled component by default but we didn't update examples to reflect that so they look broken in the styleguide now. cf-component-heading and cf-component-text usage is already ok. I didn't fix the usage of button in cf-component-form because it's done in https://github.com/cloudflare/cf-ui/pull/133 instead.
> Fix cf-component-button usage in examples

- .babelrc
- package.json
- packages/cf-component-box/.npmignore
- packages/cf-component-box/README.md
- packages/cf-component-box/example/basic/component.js
- packages/cf-component-box/package.json
- packages/cf-component-box/src/Box.js
- packages/cf-component-box/src/BoxTheme.js
- packages/cf-component-box/src/index.js
- packages/cf-component-box/src/propertiesSpec.js
- packages/cf-component-box/test/Box.js
- packages/cf-component-box/test/__snapshots__/Box.js.snap
- yarn.lock
We're embarking on a massive overhaul of some recent feature work and I'd like to clean house while we have the chance. I'd like to avoid the further proliferation of div and span with custom css in our growing codebase. 
This is sort of a stop gap as we implement fela in all of our cf-ui components and work out the kinks in usage, which may take a little time. The cf-component-flex overhaul was super awesome, and fixed most of the styling problems we hit in our recent LB work.
My thinking is that replacing the usage of a single component in several places will be easier to undo than transitioning a ton of css to css-in-js. To make this component conducive to that, the interface is identical to a fela rule.
I'm not super fond of the name box, but I could really thing of a better name. …
> Styling component similar to cf-component-flex

- packages/cf-component-button/src/Button.js
- packages/cf-component-button/src/ButtonGroup.js
- packages/cf-component-heading/src/HeadingCaption.js
- packages/cf-component-notifications/test/Notification.js
- packages/cf-component-pagination/src/Pagination.js
- packages/cf-component-pagination/src/PaginationItem.js
- packages/cf-component-text/src/Text.js
This PR revert functional components back to ES6 classes. The reasons are:
1. We need the refs for form components because we are using redux-form on the product.
2. All of the cf-ui components were in ES6 classes, which gives us refs. Nobody was complaining about them.
3. cf-ui itself is using refs now in [4 different places](https://github.com/cloudflare/cf-ui/search?utf8=%E2%9C%93&q=ref&type=)
4. Refs are needed, when we need to focus or deal with text selection or animation. I'm fine to selectively convert some to functional components if we can identify a list of components that we have a high degree of certainty that we'll never need refs for, which usually are non-interactive components. Form controls, links, tabs, dropdowns, and tables probably need to be in classes. Let's have …
> Back to ES6 classes

- packages/cf-component-button/README.md
- packages/cf-component-button/example/basic/component.js
- packages/cf-component-button/src/Button.js
- packages/cf-component-button/src/ButtonGroup.js
- packages/cf-component-button/test/ButtonGroup.js
- packages/cf-component-button/test/__snapshots__/Button.js.snap
- packages/cf-component-button/test/__snapshots__/ButtonGroup.js.snap
The original button CSS styles had this rule:
```css
'& + &': {
marginLeft: '0.4rem'
}
```
If you put two cf-component-buttons next to each other, the right one would get the left margin. However, this selector doesn't work with Fela since all classNames are random and atomic. So we need a different solution.
This PR adds a new prop `spaced` to the component `<ButtonGroup>`, so if you want to have spaces between `<Button>`s wrap them by `<ButtonGroup spaced>...</ButtonGroup>`.
Also, I made the `styles` function a little bit cleaner with `...function()` replacing `Object.assign()`.
> Spaced ButtonGroup

- packages/cf-component-card/src/CardDrawers.js
When the local state was added to the `CardDrawers` component we failed
at passing the prop back up to the parent causing the drawers not
opening when the links are clicked.
This patch passes the id up to the `onClick` function when a link is
clicked.
Fixes #159
> Card: Pass the id of the drawer clicked to parent

- README.md
There have been a lot of discussions decided recently based to the fact that *"we're the only consumers of cf-ui"*. If this is the case, let's make this an explicit recommendation.
Feel free to suggest alternate copy 😄
> Update README to recommend against external usage

- packages/cf-component-box/src/propertiesSpec.js
We currently fail our CI on invalid PropTypes, and this is stopping us use cf-component-box for a lot of use cases. Would be nice to have!
> #170 Fix cf-component-box fontSize proptype

- packages/cf-component-button/package.json
- packages/cf-component-button/src/ButtonTheme.js
- packages/cf-component-form/package.json
- packages/cf-component-form/src/FormFieldErrorTheme.js
- packages/cf-component-form/src/FormFieldsetTheme.js
- packages/cf-component-form/src/FormFooterTheme.js
- packages/cf-component-form/src/FormHeaderTheme.js
- packages/cf-component-form/src/FormLabelTheme.js
- packages/cf-component-form/src/FormTheme.js
- packages/cf-component-heading/src/HeadingCaptionTheme.js
- packages/cf-component-pagination/src/PaginationItemTheme.js
- packages/cf-component-pagination/src/PaginationLinkTheme.js
- packages/cf-component-pagination/src/PaginationRootTheme.js
- packages/cf-component-pagination/src/PaginationTheme.js
- packages/cf-component-text/package.json
- packages/cf-component-text/src/TextTheme.js
- packages/cf-style-const/README.md
- packages/cf-style-const/src/index.js
- packages/cf-style-container/README.md
- packages/cf-style-container/src/index.js
- `cf-style-container` is a "toolbox" for writing Fela based components, so it's a natural place for this function
- we will be able to remove `cf-style-const` dependency from all our packages except `cf-style-provider`, components should access these consts (variables) through `this.context.theme`, even better through HOCs in `cf-style-provider` like `createComponent()` that passes `this.context.theme` into `props.theme`
- we will be updating `cf-style-const` frequently so lerna prompts updates for all fela components very often (all fela components has `cf-style-const` as dependency)
- `cf-style-container` should be very stable (very few releases) and it should be the only dependency for all Fela components
I hope it makes sense. // @hturan related to my PR review
> Move checkBaseTheme from cf-style-const to cf-style-container

- packages/cf-style-const/src/variables.js
Adding the style guide colors into the consts. The names were proposed by designers. Every new design should use only these colors. If not push back. This is a fresh start for colors.
> Add styleguide colors

- packages/cf-component-tooltip/src/Tooltip.js
This fixes #171. Currently, the tooltip never updates to reflect new props. With this change, it'll compare props and re-create the tooltip if needed.
> #171 Update cf-component-tooltip to re-render when props change

- packages/cf-component-box/src/propertiesSpec.js
- packages/cf-component-heading/src/HeadingTheme.js
This fix is brought to you by the @Microsoft typescript compiler:
```
packages/cf-component-heading/src/HeadingTheme.js(10,3): error TS1117: An object literal cannot have multiple properties with the same name in strict mode.
```
```
packages/cf-component-box/src/propertiesSpec.js(454,3): error TS1117: An object literal cannot have multiple properties with the same name in strict mode.
```
> Remove duplicate keys

- packages/cf-builder-card/test/__snapshots__/cardBuilder.js.snap
- packages/cf-component-card/src/Card.js
- packages/cf-component-card/test/__snapshots__/Card.js.snap
In our current dashboard, lots of cards have an id prop which allows us to hash-scroll to them. This PR allows us to do the same thing with React `Card`s 🎉
Setting `id={undefined}` is fine, as React will just ignore and not render the `id` prop.
> Add support for 'id' prop on Card component

- packages/cf-style-const/src/variables.js
This is a continuation on https://github.com/cloudflare/cf-ui/pull/203. I will deprecate now `colorGrayLightOnboarding` and remove it after migration to `moonshine`
> introduce new gray color moonshine

- packages/cf-component-button/src/Button.js
We can render a button without a `onClick` function and this patch will make sure we don't get prop types errors while developing.
> button: make `onClick` optional

- packages/cf-component-page/src/PageHeader.js
- packages/cf-component-page/test/__snapshots__/PageHeader.js.snap
This is a super-simple SEMVER-major PR to make `cf-component-page`'s `PageHeader` render it's `subtitle` prop as an `h2`.
I've run `npm run update-snapshot` and committed the changes for `cf-component-page`. Is this correct? I couldn't find any documentation about how to do this so just picked the most relevant `script` 😄
> Update PageHeader to render subtitle as an h2

- packages/cf-component-pagination/src/PaginationItemMinimalTheme.js
- packages/cf-component-pagination/src/PaginationItemTheme.js
- packages/cf-component-pagination/test/__snapshots__/PaginationItem.js.snap
dots looks weird with fontSize 15px, font size should be an even number.
with fontSize 15px:
with fontSize 16px:
After this change we could set fontSize to 16px on the parent container.
> Use em for 'dots' pagination

- packages/cf-component-pagination/src/PaginationItemMinimalTheme.js
Make em bigger.
I took the value from our existing codebase and it looks like this:
> fix: make the margins between pagination items larger

- packages/cf-util-http/src/http.js
- packages/cf-util-http/test/http.js
The fetch promise resolves to a stream with methods such as text() and json(). These methods cannot be called twice, and text() is called internally in the request method. This means that response body can only be accessed in the callback and not via the object resolved by the promise.
This PR updates the request method so that the promise resolves with the same object that's passed to the success callback, and throws with the same object that's passed to the error callback.
> Update cf-util-http so the promises returned resolve to json

- .gitignore
TLDR; This PR ignores the auto generated NPM5 `package-lock.json` file.
Not that NPM@5 is out, it generates a `package-lock.json` file by default. But since we're using yarn we don't need the `package-lock.json`. 
If anyone feels strongly about committing the `package-lock.json` to the repo, I'll open another PR that commits the `package-lock.json` files.
> Added package-lock.json to gitignore

- packages/cf-builder-pagination/test/__snapshots__/PaginationBuilder.js.snap
- packages/cf-component-pagination/test/__snapshots__/Pagination.js.snap
- packages/cf-component-pagination/test/__snapshots__/PaginationItem.js.snap
- packages/cf-style-container/package.json
- packages/cf-style-container/src/index.js
- packages/cf-style-container/test/__snapshots__/index.js.snap
- packages/cf-style-provider/package.json
- packages/cf-style-provider/src/index.js
- packages/cf-style-provider/test/__snapshots__/index.js.snap
- packages/cf-style-provider/test/index.js
:star: New major version of CSS-in-JS Fela [just landed](https://twitter.com/rofrischmann/status/872552144045559808) :star:
**This PR updates cf-ui to v5:**
- it removes `id={undefined}` and `style={undefined}` from our snapshots
- `react-fela/connect` has a new API that matches our `cf-style-provider/createComponentStyles` perfectly, so that is updated
- font renderer is deprecated and replaced by [fela-plugin-embedded](https://github.com/rofrischmann/fela/tree/master/packages/fela-plugin-embedded), @koddsson should like this
- no need to specify style nodes, fela is now smarter and creates its own nodes automatically (one node for rules, one node for every media query, one node for fonts, ... -> better performance)
- should remove a lot of React.PropType warnings, there are still some …
> CSS-in-JS Fela v5

- packages/cf-component-button/src/Button.js
- packages/cf-component-button/test/__snapshots__/Button.js.snap
- packages/cf-component-button/test/__snapshots__/ButtonGroup.js.snap
This allows the browser to add it's default focus state to the button
> This makes the button active state the default browser focus state

- packages/cf-style-container/package.json
- packages/cf-style-container/src/index.js
- packages/cf-style-container/test/index.js
merge-options 1.0.0 has a package.json file that just assumes the environment will only be node, this PR swaps it out with seamless-immutable, so the themes merged now are immutable and deeply cloned.
> Replace merge-options with seamless-immutable

- packages/cf-component-form/src/Form.js
We removed the `background` property from the theme 46cbe7b but forgot
to remove it from the component as well.
I realized just as I hit merge on #272  😭
> fix(cf-component-form): remove missing background

- CONTRIBUTING.md
- package.json
- yarn.lock
Add the packages `husky` and `validate-commit-msg` to create a precommit
git hook that rejects commits that do not adhere to the conventional
commits standard[1].
This enables us to run `lerna publish` with the flag
`--conventional-commits` which will autogenerate a changelog and set the
package versions automatically. This PR enables this flag.
[1]: https://conventionalcommits.org/
Closes: #237
> chore(tooling): force conventional commits

- packages/cf-builder-pagination/test/PaginationBuilder.js
- packages/cf-style-container/package.json
- packages/cf-style-container/src/createComponent.js
- packages/cf-style-container/src/index.js
This prevents to append custom classNames to components styled by Fela.
It gives a warning: 
```
You cannot restyle Fela component ${componentName}
```
> Stop passing rule functions downstream

- packages/cf-component-page/src/Page.js
- packages/cf-component-page/src/PageTheme.js
- packages/cf-component-page/src/index.js
- packages/cf-component-page/test/__snapshots__/Page.js.snap
There's already padding by way of zone-nav, so this adds way too much.
I'm whitelisting it and making it overridable via theme in case it
needs tweaking on some pages.
> Removing top padding from page

- packages/cf-component-toggle/src/Toggle.js
- packages/cf-component-toggle/src/ToggleTheme.js
- packages/cf-component-toggle/src/index.js
- packages/cf-component-toggle/test/Toggle.js
- packages/cf-component-toggle/test/__snapshots__/Toggle.js.snap
Now `cf-component-toggle` uses `fela` to apply styles defined in JS to
the components rather than relying on outside CSS to provide styles.
BREAKING CHANGE: `className` prop is no longer applied to the component.
Closes: #228
> feat(cf-component-toggle): rewrite in `fela`

- packages/cf-component-form/src/FormFieldset.js
- packages/cf-component-form/test/__snapshots__/FormFieldset.js.snap
- packages/cf-style-provider/README.md
- packages/cf-style-provider/src/createRenderer.js
- packages/cf-style-provider/src/whitelistMediaQuery.js
By default, Fela doesn't preserve order of anything but it's important for media queries. This PR adds sorting for media queries. Also, we need to limit ourselves to use only specific set of them so the sorting is possible and the result can be deterministic. Once you start mix min-width, max-width or even both, things get crazy fast. Therefore, you should always use one of the predefined aliased min-width breakpoints:
```
mobile: @media (min-width: 13.6em)
mobileWide: @media (min-width: 30.4em)
tablet: @media (min-width: 47.2em)
desktop: @media (min-width: 64em)
desktopLarge: @media (min-width: 97.6em)
```
use it as: 
```js
createComponent(() => ({
desktop: {
}
});
```
and never write something as:
```js
createComponent(() => ({
'@media ....' : {
}
});
```
again. 
All our media queries …
> Sort Media Queries and whitelist them

- packages/cf-component-toggle/package.json
`cf-style-container` was missing from the dependency list
> fix(cf-component-toggle): add missing dependency

- packages/cf-component-callout/src/Callout.js
- packages/cf-component-callout/src/CalloutTheme.js
Remove hard-coded values in the component `cf-component-callout` and move into the default theme so that they can be overwritten.
> fix(cf-component-callout): get all rules in theme

- packages/cf-component-progress/example/basic/component.js
- packages/cf-component-progress/src/Progress.js
- packages/cf-component-progress/test/__snapshots__/Progress.js.snap
Media queries in `cf-ui` are reversed to the ones in the legacy CSS
styles resulting in mobile styles being applied when the browser width
is larger than a average mobile device and the desktop styles being
applied when smaller than the average mobile device.
This PR reversed the styles along the media query "axis". So the correct
device styles are applies for the Progress component.
> fix(cf-component-progress): media query fix

- packages/cf-style-container/src/createComponent.js
Change the component display name for fela higher order components so
that the actual components can be targeted by their display names in
tests or otherwise.
BREAKING CHANGE: If you are targeting components in your tests you are
going to need to make some changes. Previously others have selected the
second one in the node list after querying for the display name.
> fix(cf-style-container): Change fela wrapper names

- packages/cf-style-container/src/index.js
- packages/cf-style-container/test/index.js
Sets the `displayName` property of themed components to
`Themed[Component name]` rather than the `ThemedComponent` it is set to
now.
This change will make it possible to select these components in
`enzyme` tests by their display names.
BREAKING CHANGE: The display name of themed components now have a
`Themed` prefix to their display names. So if you had a themed component
that has the name `Button` it will now be `ThemedButton` instead of
`ThemedComponent`.
Related-to: #300
> fix(cf-style-container): set themed component name

- packages/cf-component-dropdown/src/Dropdown.js
- packages/cf-component-dropdown/src/DropdownLink.js
- packages/cf-component-dropdown/src/DropdownLinkTheme.js
- packages/cf-component-dropdown/src/DropdownSeparator.js
- packages/cf-component-dropdown/src/DropdownSeparatorTheme.js
- packages/cf-component-dropdown/src/DropdownTheme.js
- packages/cf-component-dropdown/src/index.js
- packages/cf-component-dropdown/test/Dropdown.js
- packages/cf-component-dropdown/test/DropdownLink.js
- packages/cf-component-dropdown/test/DropdownSeparator.js
- packages/cf-component-dropdown/test/__snapshots__/Dropdown.js.snap
- packages/cf-component-dropdown/test/__snapshots__/DropdownLink.js.snap
- packages/cf-component-dropdown/test/__snapshots__/DropdownSeparator.js.snap
BREAKING CHANGE: Major migration of styles from plain old CSS class
names to the CSS-in-JS framework `fela`.
Closes: #210
> feat(cf-component-dropdown): CSS to `fela`

- packages/cf-component-form/README.md
- packages/cf-component-form/example/basic/component.js
- packages/cf-component-input/example/basic/component.js
- packages/cf-component-input/src/Input.js
- packages/cf-component-input/src/InputTheme.js
- packages/cf-component-input/src/index.js
- packages/cf-component-input/test/Input.js
- packages/cf-component-input/test/__snapshots__/Input.js.snap
BREAKING CHANGE: There is no default export in `cf-component-input`
anymore, the previously exported default is now exported as `Input`.
Additionally the `className` prop is now ignored.
Closes: #226
> feat(cf-component-input): rewrite styling in fela

- packages/cf-component-input/src/Input.js
Instead of maintaning a 1-to-1 list of props that HTMLInputElement can accept we should just spread the ones we get from the parent on the `<input />` component.
> fix(cf-component-input): spread input props

- package.json
- packages/cf-style-provider/src/createRenderer.js
Default value will be empty so no changes to the current behavior. We allow passing value through input parameter in case we need to use prefix (in case of class name collision)
> Allow passing selectorPrefix into cf-style-provider

- packages/cf-style-container/README.md
- packages/cf-style-container/src/index.js
- packages/cf-style-container/test/index.js
I've added two new HOCs. They are handy for integration with third party stuff. 
A HOC that passes the current theme from context into the prop `theme`. This is useful
when you need to access the theme without using `createComponent`. In other words,
you can't create a new styled component with it.
```jsx
import { withTheme } from 'cf-style-container';
const MyComponent = ({ theme }) => <div>Color: {theme.colors.hail}</div> 
export default withTheme(MyComponent);
```
A HOC that passes the renderer from context into the prop `renderer`. This is useful
for third party integration when you need to generate a class name and you can't create
a new styled component with it.
```jsx
import { withRenderer } from 'cf-style-container';
const MyComponent = ({ theme }) => {
const styles = props => ({ …
```
> Add withTheme and withRenderer into cf-style-container

- packages/cf-component-form/src/FormFieldset.js
I saw that in our example, this component was failing validation since this prop was missing (and it's specified as required). However, it's not _really_ required. The component defaults to `vertical`. Well, that's not exactly true. All input that isn't `horizontal` is treated as `vertical`.
> fix(cf-component-form): FormFieldset invalid propTypes

- packages/cf-component-input/src/Input.js
- packages/cf-component-input/src/InputTheme.js
- packages/cf-component-input/test/__snapshots__/Input.js.snap
In fela we need to whitelist all the props we want to be passed down to the wrapped component.
This PR adds the `disabled` property to the prop types of the `Input` component.
> feat(cf-component-input): allow flex on input

- packages/cf-component-input/example/basic/component.js
- packages/cf-component-input/src/Input.js
- packages/cf-component-input/test/__snapshots__/Input.js.snap
In fela we need to whitelist all the props we want to be passed down to the wrapped component.
This PR adds the `disabled` property to the prop types of the `Input` component.
> feat(cf-component-input): allow disabled on input

- packages/cf-component-tabs/src/Tabs.js
- packages/cf-component-tabs/src/TabsTheme.js
- packages/cf-component-tabs/test/__snapshots__/Tabs.js.snap
In #314 we errounisly made assumptions where colors are kept in the
theme. Trying to access the white color at `theme.color.white` and the
smoke color at `theme.color.smoke` resulted in `undefined` values that
`fela` swallows up and not emitting a rule.
This patch references the colors in the correct location as well as
minor housekeeping to keep the tabs theme a bit tidier.
> fix(cf-component-tabs): set the correct colors

- packages/cf-component-input/src/Input.js
- packages/cf-component-input/src/InputTheme.js
- packages/cf-component-input/test/__snapshots__/Input.js.snap
In fela we need to add all properties we'd like to override with other values into the component.
This PR adds the `text-indent` key to the style object of the Input component.
> feat(cf-component-input): allow text-indent on input

- CODEOWNERS
Adding the code reviewers is a tedious part of opening up a PR in cf-ui.
This patch adds users as "Code Owners" of all the files in the repo so
that they get added as default reviewers for every PR that's opened.
See https://github.com/blog/2392-introducing-code-owners for more info.
> chore: add default code reviewers

- packages/cf-component-tabs/example/basic/component.js
- packages/cf-component-tabs/src/Tabs.js
- packages/cf-component-tabs/src/TabsItem.js
- packages/cf-component-tabs/src/TabsItemTheme.js
- packages/cf-component-tabs/src/TabsTheme.js
- packages/cf-component-tabs/src/index.js
In order to be able to apply styles to a "tab item" we need to abstract
it out into it's own component. That can be optionally be passed down to
the `Tabs` component defaulting to the styles previously applied.
This change is backwards compatible. See
`packages/cf-component-tabs/example/basic/component.js` for the optional
component property.
> feat(cf-component-tabs): `TabsItem` own component

- packages/cf-component-tabs/src/TabsItem.js
- packages/cf-component-tabs/src/TabsItemTheme.js
Even tho the current theme doesn't make any distinction on colors when a
item is selected or not there are instances in the dashboard where we'd
like to do exactly that. Unfortunately due to the styling model we have
now we need to specifically list out any possible rules we might use
when the component is implemented, warranting this change.
> feat(cf-component-tabs): selected color override

- packages/cf-component-tabs/src/Tabs.js
- packages/cf-component-tabs/src/TabsTheme.js
- packages/cf-component-tabs/test/__snapshots__/Tabs.js.snap
Split up the `border` shorthand into `borderWidth`, `borderStyle` and
`borderColor` so that it can be overwritten more easily. The
`borderWidth` shorthand takes in either a number or a string conforming
to the normal rules of CSS.
For example if we wanted all the borders
except for the one on the bottom we could do something like:
1px 1px 0 1px
> feat(cf-component-tabs): allow overriding border

- packages/cf-component-input/src/Input.js
- packages/cf-component-input/test/__snapshots__/Input.js.snap
I've also removed `isRequired` from `value`, since it's not always required.
> Add defaultValue prop type to cf-component-input

- packages/cf-component-radio/src/Radio.js
- packages/cf-component-radio/src/RadioTheme.js
- packages/cf-component-radio/test/__snapshots__/Radio.js.snap
Previously we only allowed `marginTop` and `paddingLeft` to be
overridden but we want to override the whole shorthand in some places
where this component is implemented.
> fix(cf-component-radio): allow padding/margin override

- packages/cf-util-http/src/http.js
- packages/cf-util-http/src/index.js
before in transpiled index.js:
```
var _http = require('./http');
Object.keys(_http).forEach(function (key) {
if (key === "default" || key === "__esModule") return;
Object.defineProperty(exports, key, {
enumerable: true,
get: function get() {
return _http[key];
}
});
});
require('./polyfillFetchInEdge');
```
after in transpiled http.js:
```
require('./polyfillFetchInEdge');
require('isomorphic-fetch');
```
I needed to run `require('./polyfillFetchInEdge'` before `require('isomorphic-fetch')` in order to polyfill `fetch` in Edge browser.
> Fetch polyfill fix for Edge: correct order of requires in transpiled code

- .travis.yml
- README.md
This patch will instruct the CI system to run a deploy command (yarn run publish -- --yes) when a commit lands on the `master` branch.
This will mean that developers won't have to run these commands from local machines to publish packages anymore.
> chore(deployment): Automatically publish packages

- .travis.yml
In 264539a we set up some pretty sweet continues deployment system but erroneously set the deployment branch to `production` when our "production" branch is in fact called "master".
This patch changes the Travis "deploy" branch to `master.
> chore(deployment): publish from the master branch

- .travis.yml
Apparently, we need to install all dependencies before deploying since the deployment steps run in a different context than the previous build and tests contexts.
> chore(deployment): install deps before deploying

- packages/cf-component-form/example/basic/component.js
- packages/cf-component-select/example/async/component.js
- packages/cf-component-select/example/basic/component.js
- packages/cf-component-select/src/Select.js
- packages/cf-component-select/src/SelectTheme.js
- packages/cf-component-select/src/index.js
- packages/cf-component-select/test/Select.js
- packages/cf-component-select/test/__snapshots__/Select.js.snap
- packages/cf-component-tabs/src/Tabs.js
Migrate the `cf-component-select` component to use the CSS-in-JS
framework fela.
Closes: #213
> feat(cf-component-select): migrate select to fela

- packages/cf-component-button/src/Button.js
- packages/cf-component-button/src/ButtonGroup.js
- packages/cf-component-button/test/__snapshots__/Button.js.snap
- packages/cf-component-button/test/__snapshots__/ButtonGroup.js.snap
This PR adds a `vertical` prop to `ButtonGroup`, allowing for vertical groups of buttons, as seen in the below screenshot:
> Added 'vertical' prop to ButtonGroup

- packages/cf-style-const/src/variables.js
This adds a new color to `cf-style-const` named 'cherry'.
> feat(cf-style-const): add 'cherry' color

- packages/cf-component-button/src/Button.js
- packages/cf-component-button/src/ButtonTheme.js
- packages/cf-component-button/test/__snapshots__/Button.js.snap
- packages/cf-component-button/test/__snapshots__/ButtonGroup.js.snap
- packages/cf-style-container/test/__snapshots__/index.js.snap
This PR adds a new `dangerOutline` button type, useful for low-contrast warning actions.
> feat(cf-component-button): add 'dangerOutline' button type

- packages/cf-component-select/src/Select.js
BREAKING CHANGE: because it didn't update the version correctly last time
> fix(cf-component-select): Bump version. 

- packages/cf-style-container/README.md
- packages/cf-style-container/src/index.js
- packages/cf-style-container/test/index.js
A HOC that applies a string of static styles to a component using fela's renderStatic. Useful for integration with older libraries that require side loading of a static CSS block.
> feat(cf-style-container): add applyStaticStyles method
