karma.conf.js

Typo in saucelabs config

---

example/styles.css
packages/cf-component-card/example/basic/component.js
packages/cf-component-card/src/CardContent.js
packages/cf-component-card/test/CardContent.js
packages/cf-component-copyable-textarea/src/CopyableTextarea.js
packages/cf-util-text/src/text.js

**This is the result**
I added footer message because it was missing in cf-ui and was present in cloudflare.com
**Example of footer messages in cloudflare.com**
[image1]: http://i.imgur.com/DpY9fzl.png 
[image2]: http://i.imgur.com/3o1fqa5.png

Added footer message for cf-component-card/CardContent

---

packages/cf-component-form/README.md

Seems to me that we should have the npm package name in the require rather than the relative path :P

Fix import in example

---

example/styles.css
packages/cf-component-modal/example/basic/component.js
packages/cf-component-modal/src/Modal.js

Add a wide modifier to Modal component

---

packages/cf-util-http/README.md

Fixes the http signature in the readme

Update cf-http-util readme

---

example/styles.css
packages/cf-component-copyable-textarea/package.json
packages/cf-component-select/example/async/component.js
packages/cf-component-select/example/basic/component.js
packages/cf-component-select/src/Select.js

Support react-select [async options](https://github.com/JedWatson/react-select#async-options)
This lets consumers set async options for Select. This is for integrating api queries for auto suggestions

Support async select

---

example/styles.css
packages/cf-component-toggle/example/basic/component.js
packages/cf-component-toggle/src/Toggle.js
packages/cf-component-toggle/test/Toggle.js

Support disabled toggles

---

packages/cf-component-textarea/src/Textarea.js

[TextArea] Pass any prop down to inner component

---

packages/cf-component-flex/package.json
packages/cf-component-flex/src/Flex.js
packages/cf-component-flex/src/FlexItem.js
packages/cf-component-flex/test/Flex.js
packages/cf-component-flex/test/FlexItem.js

So we can use this component to do complex layout semantically rather than sprinkling divs with non-prefixed inline styles all over the place.

Gimme all the flex props

---

packages/cf-component-modal/example/basic/component.js
packages/cf-component-modal/src/Modal.js
packages/cf-component-modal/test/Modal.js

Adds an 'extra-wide' option to modal.

---

packages/cf-component-select/src/Select.js

I could also c/p the props from the react-select documentation if we'd prefer that :D

Send all props down to react-select.

---

package.json
packages/cf-component-table/src/TableCell.js
packages/cf-component-table/src/TableHeadCell.js
packages/cf-component-table/src/TableRow.js

Part of #46 
This PR allows arbitrary props to be passed down to `<tr>`, `<td>`, and `<th>`.

Allow table rows and cells to accept arbitrary props

---

packages/cf-component-button/test/__snapshots__/Button.js.snap
packages/cf-component-button/test/__snapshots__/ButtonGroup.js.snap
packages/cf-component-heading/test/__snapshots__/HeadingCaption.js.snap
packages/cf-component-text/test/__snapshots__/Text.js.snap

quick fix for https://github.com/cloudflare/cf-ui/issues/112

Update jest snapshots after release of the fela packages

---

packages/cf-component-callout/src/Callout.js

I also changed title to be not required.

Allow nodes as content in cf-component-callout

---

packages/cf-util-http/src/http.js
packages/cf-util-http/test/http.js

https://github.com/cloudflare/cf-ui/issues/126

Issue #126 make optional param really optional

---

packages/cf-component-box/src/propertiesSpec.js

Missed a few with the first pass

Adds border and vertical-align to cf-component-box

---

packages/cf-component-notifications/test/Notification.js

- I will sync the fix into master from legacy.
- fixes https://github.com/cloudflare/cf-ui/issues/96

Fix flaky test for cf-component-notifications

---

packages/cf-component-notifications/test/Notification.js

- due to [merge conflicts](https://github.com/cloudflare/cf-ui/pull/155) I cherry pick the fix from legacy

cherry-pick fix for flaky test into master

---

README.md
example/package.json
example/source.js
example/yarn.lock

- update example so it uses the latest button (where the styled version is exported by default)
- make it even more condense

Update example and main readme

---

package.json
packages/cf-builder-pagination/test/PaginationBuilder.js
packages/cf-style-provider/src/index.js
packages/cf-style-provider/test/__snapshots__/index.js.snap
packages/cf-style-provider/test/index.js
yarn.lock

Solves skipped tests for @sejoker. I also added a full integration test for Fela within cf-style-provider.

Styleprovider: pass props through and more tests

---

packages/cf-util-http/src/http.js
packages/cf-util-http/src/index.js
packages/cf-util-http/src/polyfillFetchInEdge.js

reverted changes to logic with Headers for Edge, polyfill fetch for Edge instead

Polyfill fetch in Edge browser

---

packages/cf-style-const/src/variables.js

Added all gradient colors from our styleguide, default boxShadow and main background color.

Add some new constants

---

packages/cf-builder-pagination/test/__snapshots__/PaginationBuilder.js.snap
packages/cf-component-pagination/example/basic/component.js
packages/cf-component-pagination/src/PaginationItem.js
packages/cf-component-pagination/src/PaginationItemTheme.js
packages/cf-component-pagination/src/PaginationLink.js
packages/cf-component-pagination/src/PaginationLinkTheme.js
packages/cf-component-pagination/src/PaginationTheme.js
packages/cf-component-pagination/test/PaginationItem.js
packages/cf-component-pagination/test/__snapshots__/Pagination.js.snap
packages/cf-component-pagination/test/__snapshots__/PaginationItem.js.snap

Pagination item type dot

---

packages/cf-component-button/src/Button.js
packages/cf-style-container/README.md
packages/cf-style-container/package.json
packages/cf-style-container/src/index.js
packages/cf-style-container/test/__snapshots__/index.js.snap
packages/cf-style-container/test/index.js

- allows to override styles from the default (main) theme.

pass customTheme optional parameter to override styles from mainTheme

---

package.json
yarn.lock

Seems to not make all the tests fail :laughing:
Fixes: #195

deps: update jest

---

packages/cf-component-select/package.json
packages/cf-component-select/test/__snapshots__/Select.js.snap

https://github.com/JedWatson/react-select/pull/1658

Update react-select to 1.0.0-rc.4 for react 15.5 support for cf-component-select

---

packages/cf-builder-pagination/test/__snapshots__/PaginationBuilder.js.snap
packages/cf-component-pagination/src/PaginationItemTheme.js
packages/cf-component-pagination/test/__snapshots__/PaginationItem.js.snap
packages/cf-style-provider/package.json

use pagination background color from the new design colors

---

packages/cf-style-const/src/variables.js

This is a request from the design team to introduce new light gray color.

introduce new light gray color dessy

---

packages/cf-component-card/src/CardContent.js

card/content: make title optional

---

packages/cf-component-page/src/PageHeader.js
packages/cf-component-page/test/__snapshots__/PageHeader.js.snap

cf-component-page subtitle

---

packages/cf-component-heading/src/Heading.js
packages/cf-component-heading/src/HeadingTheme.js
packages/cf-component-heading/test/__snapshots__/Heading.js.snap

I need padding so I can overwrite using custom styles in tables. This is a blocker for the Fela www-next migration so would appreciate a review.

Added padding for heading

---

packages/cf-component-button/src/Button.js
packages/cf-component-button/test/__snapshots__/ButtonGroup.js.snap

This fixes an edge case where the border radius of spaced button is not maintained.

Fix for border radius for spaced buttons

---

packages/cf-component-button/src/Button.js
packages/cf-component-button/src/ButtonTheme.js
packages/cf-component-button/test/__snapshots__/Button.js.snap
packages/cf-component-button/test/__snapshots__/ButtonGroup.js.snap

Need this height to override the theme in a few places.

Added height to theme to override

---

packages/cf-style-const/src/variables.js

base theme new color for important information blocks

---

packages/cf-style-provider/package.json
packages/cf-style-provider/src/index.js
packages/cf-style-provider/test/__snapshots__/index.js.snap

So now we can have some default mobile first break points with nice names

fela named-media-query-plugin

---

packages/cf-component-form/src/FormTheme.js
packages/cf-component-form/test/__snapshots__/Form.js.snap

Removes the white form background color.

fix(cf-component-form): remove background color

---

packages/cf-component-page/example/basic/component.js
packages/cf-component-page/src/Page.js
packages/cf-component-page/src/PageContent.js
packages/cf-component-page/src/PageHeader.js
packages/cf-component-page/src/index.js
packages/cf-component-page/test/Page.js
packages/cf-component-page/test/PageContent.js
packages/cf-component-page/test/PageHeader.js
packages/cf-component-page/test/__snapshots__/PageContent.js.snap
packages/cf-component-page/test/__snapshots__/PageHeader.js.snap
packages/cf-style-const/src/variables.js
packages/cf-style-container/test/__snapshots__/index.js.snap
packages/cf-style-provider/src/index.js

This does a few things:
1. Migrates Page to fela
2. Adds a new PageContent component for handling horizontal spacing

Migrate Page to fela and add PageContent component

---

packages/cf-style-container/README.md

Updated the readme to include some docs on the recently added functions.

Update cf-style-container README

---

package.json

We are already in independant mode, see `lerna.json` in the project root.

Remove --independent flag

---

package.json

This reverts commit 95f649196e5d2019404bc45ed62386353c3d93f8.

chore: Revert "fix(husky): disable husky"

---

packages/cf-builder-pagination/test/__snapshots__/PaginationBuilder.js.snap
packages/cf-component-box/test/__snapshots__/Box.js.snap
packages/cf-component-button/test/__snapshots__/Button.js.snap
packages/cf-component-button/test/__snapshots__/ButtonGroup.js.snap
packages/cf-component-form/test/__snapshots__/Form.js.snap
packages/cf-component-form/test/__snapshots__/FormFieldError.js.snap
packages/cf-component-form/test/__snapshots__/FormFieldset.js.snap
packages/cf-component-form/test/__snapshots__/FormFooter.js.snap
packages/cf-component-form/test/__snapshots__/FormHeader.js.snap
packages/cf-component-form/test/__snapshots__/FormLabel.js.snap
packages/cf-component-heading/test/__snapshots__/Heading.js.snap
packages/cf-component-heading/test/__snapshots__/HeadingCaption.js.snap
packages/cf-component-label/test/__snapshots__/Label.js.snap
packages/cf-component-page/test/__snapshots__/Page.js.snap
packages/cf-component-page/test/__snapshots__/PageContent.js.snap
packages/cf-component-page/test/__snapshots__/PageHeader.js.snap
packages/cf-component-pagination/test/__snapshots__/Pagination.js.snap
packages/cf-component-pagination/test/__snapshots__/PaginationItem.js.snap
packages/cf-component-text/test/__snapshots__/Text.js.snap
packages/cf-component-toggle/test/__snapshots__/Toggle.js.snap
packages/cf-style-container/test/__snapshots__/index.js.snap
packages/cf-style-provider/package.json
packages/cf-style-provider/src/createRenderer.js
packages/cf-style-provider/test/__snapshots__/index.js.snap

This removes monolithic (single classNames) mode for the class name generation so the production, dev and tests (snapshots) are all using the same atomic classnames.

Disable monolithic in the dev and test env

---

packages/cf-component-callout/README.md
packages/cf-component-callout/example/basic/component.js
packages/cf-component-callout/src/Callout.js
packages/cf-component-callout/src/CalloutTheme.js
packages/cf-component-callout/src/index.js
packages/cf-component-callout/test/Callout.js
packages/cf-component-callout/test/__snapshots__/Callout.js.snap

BREAKING CHANGE: Internals have been rewritten in a significant way.
This warrants a breaking change version bump.
Closes: #216

feat(cf-component-callout): rewrite styles in fela

---

packages/cf-component-progress/README.md
packages/cf-component-progress/src/Progress.js
packages/cf-component-progress/src/ProgressTheme.js
packages/cf-component-progress/src/index.js
packages/cf-component-progress/test/Progress.js
packages/cf-component-progress/test/__snapshots__/Progress.js.snap

BREAKING CHANGE: Underlying styling have been completely re-written in `fela` warranting extra caution when updating as well as a major version bump.
Closes: #230

feat(cf-component-progress): implement in fela

---

packages/cf-component-copyable-textarea/README.md
packages/cf-component-copyable-textarea/example/basic/component.js
packages/cf-component-copyable-textarea/src/CopyableTextarea.js
packages/cf-component-copyable-textarea/src/CopyableTextareaTheme.js
packages/cf-component-copyable-textarea/src/index.js
packages/cf-component-copyable-textarea/test/CopyableTextarea.js
packages/cf-component-copyable-textarea/test/__snapshots__/CopyableTextarea.js.snap
packages/cf-component-dropdown/test/Dropdown.js
packages/cf-component-form/README.md
packages/cf-component-form/example/basic/component.js
packages/cf-component-textarea/README.md
packages/cf-component-textarea/example/basic/component.js
packages/cf-component-textarea/src/Textarea.js
packages/cf-component-textarea/src/TextareaTheme.js
packages/cf-component-textarea/src/index.js
packages/cf-component-textarea/test/Textarea.js
packages/cf-component-textarea/test/__snapshots__/Textarea.js.snap

Figured I'd do both at the same time.

Migrate textarea & copyable-textarea to fela

---

packages/cf-component-dropdown/src/Dropdown.js
packages/cf-component-dropdown/src/DropdownTheme.js
packages/cf-component-dropdown/test/__snapshots__/Dropdown.js.snap
packages/cf-component-dropdown/test/__snapshots__/DropdownLink.js.snap

Add the `text-align` CSS property to the theme for the Dropdown component so that implementing parties can overwrite that rule.

fix(cf-component-dropdown): text-align in theme

---

packages/cf-component-tabs/src/Tabs.js
packages/cf-component-tabs/src/TabsPanel.js
packages/cf-component-tabs/src/TabsPanelTheme.js
packages/cf-component-tabs/src/TabsTheme.js
packages/cf-component-tabs/src/index.js
packages/cf-component-tabs/test/Tabs.js
packages/cf-component-tabs/test/TabsPanel.js
packages/cf-component-tabs/test/__snapshots__/Tabs.js.snap
packages/cf-component-tabs/test/__snapshots__/TabsPanel.js.snap

I added a second commit that fixes this gap in the examples:
Before:
After:

Migate tabs to fela

---

.travis.yml
package.json
packages/cf-builder-card/package.json
packages/cf-builder-table/package.json
packages/cf-component-input/src/Input.js
packages/cf-component-input/test/Input.js
packages/cf-component-notifications/test/Notification.js
packages/cf-util-http/src/http.js
test_setup/patch-console.js

Cleaning up all console logs and add tests to disallow as well as trying to run tests faster on CI

Test clean up

---

packages/cf-util-http-poll/test/http.js

Getting some of this coverage up

test: add tests for the `cf-util-http-poll`

---

packages/cf-style-const/src/variables.js
packages/cf-style-container/test/__snapshots__/index.js.snap

feat(cf-style-const): Add a new color

---

packages/cf-builder-card/src/CardBuilder.js
packages/cf-builder-card/test/__snapshots__/cardBuilder.js.snap
packages/cf-builder-card/test/cardBuilder.js
packages/cf-component-dynamic-content/example/basic/component.js
packages/cf-component-dynamic-content/src/DynamicContent.js
packages/cf-component-dynamic-content/src/DynamicContentTheme.js
packages/cf-component-dynamic-content/src/index.js
packages/cf-component-dynamic-content/test/DynamicContent.js
packages/cf-component-dynamic-content/test/__snapshots__/DynamicContent.js.snap
test_setup/patch-console.js

Convert the `cf-component-dynamic-content` to fela.
Related-to: #227

feat(cf-component-dynamic-content): css2fela

---

packages/cf-component-radio/src/Radio.js
packages/cf-component-radio/src/RadioGroup.js
packages/cf-component-radio/src/RadioTheme.js
packages/cf-component-radio/src/index.js
packages/cf-component-radio/test/Radio.js
packages/cf-component-radio/test/RadioGroup.js
packages/cf-component-radio/test/__snapshots__/Radio.js.snap
packages/cf-component-radio/test/__snapshots__/RadioGroup.js.snap

BREAKING CHANGE: This change is a significant change in the component
internals warranting a major bump in version number.
Closes: #222

feat(cf-component-radio): rewrite styling in fela

---

packages/cf-component-form/src/FormFieldErrorTheme.js
packages/cf-component-form/test/__snapshots__/FormFieldError.js.snap

fix(cf-component-form): fix form field error position

---

packages/cf-builder-card/test/__snapshots__/cardBuilder.js.snap
packages/cf-component-card/src/CardToolbarLink.js
packages/cf-component-card/test/__snapshots__/CardDrawers.js.snap
packages/cf-component-card/test/__snapshots__/CardToolbarLink.js.snap
packages/cf-style-container/test/__snapshots__/index.js.snap

So some style is off in cf-styleguide. Trying to hunt it down. But the correct percentage for aligning the arrow in next is 51%.

chore(cf-component-card): Fixed top percentage for arrow

---

README.md

chore(README): Added Travis build status

---

CODEOWNERS

chore: remove jwineman and koddoson as CODEOWNERS.

---

packages/cf-component-select/package.json
packages/cf-component-select/src/CloseMenu.js
packages/cf-component-select/src/MenuHeader.js
packages/cf-component-select/src/Option.js
packages/cf-component-select/src/ScrollContainer.js
packages/cf-component-select/src/Select.js
packages/cf-component-select/src/Value.js
packages/cf-component-select/src/arrowRenderer.js
packages/cf-component-select/src/clearRenderer.js
packages/cf-component-select/src/menuRenderer.js
packages/cf-component-select/test/__snapshots__/Select.js.snap

Move all styles to fela.
Prevent page scrolling the scrolling the menu.

feat(cf-component-select): update styles

---

packages/cf-component-select/src/Select.js

fix(cf-component-select): So publishing bumps version

---

packages/cf-builder-card/test/__snapshots__/cardBuilder.js.snap
packages/cf-builder-pagination/test/__snapshots__/PaginationBuilder.js.snap
packages/cf-component-button/example/basic/component.js
packages/cf-component-card/src/CardDrawers.js
packages/cf-component-card/test/__snapshots__/CardDrawers.js.snap
packages/cf-component-header/example/basic/component.js
packages/cf-component-loading/src/Loading.js
packages/cf-component-loading/test/__snapshots__/Loading.js.snap
packages/cf-component-progress/src/Progress.js
packages/cf-component-progress/test/__snapshots__/Progress.js.snap
packages/cf-component-radio/src/RadioGroup.js
packages/cf-component-tabs/example/basic/component.js
packages/cf-component-toggle/src/Toggle.js
packages/cf-component-toggle/test/__snapshots__/Toggle.js.snap

Fixed propType warnings. Console is now clean.

So many proptype warnings

---

packages/cf-component-icon/README.md

BREAKING CHANGE: Icon now uses fela

chore(cf-component-icon): need this to get a breaking change

---

packages/cf-builder-pagination/test/__snapshots__/PaginationBuilder.js.snap
packages/cf-component-icon/src/Icon.js

Pagination is overriding color.

chore(cf-component-icon): Update to prevent color overrides

---

packages/cf-component-select/src/Select.js
packages/cf-component-select/test/__snapshots__/Select.js.snap

Also don't show the hover border when disabled, or the pointer cursor over the arrow.

fix(cf-component-select): Pass disabled property to react-select
